#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

def print_error_message
  print "[Help] Run as: ./workout_generator manage"
end

# menu_prompt = <<EOS
# 1. Add an exercise
# 2. List all exercises
# 3. Create Workout
# 4. Exit
# EOS

if ARGV.length < 1
  print_error_message
elsif ARGV.length == 1
  # Not valid argument
  if ARGV[0] != 'manage'
    print_error_message
  else
    choose do |menu|
      menu.prompt = ""

      exercise_controller = ExerciseController.new

      menu.choice('Add a Workout') { say("") }
      menu.choice('List all Exercises') { exercise_controller.index }
      menu.choice('Create Workout') { say("") }
      menu.choice('Exit') { say("Peace Out!\n") }
    end
  end
end