#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
1. Add an Exercise
2. List All Exercises
3. Create Workout
4. View Workouts
5. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  loop do
    choose do |menu|
      menu.prompt = ""

      exercise_controller = ExerciseController.new
      menu.choice('Add an Exercise') do
        loop do
          user_input = ask("What exercise would you like to add?")
          response = exercise_controller.add(user_input)
          say(response) unless response.nil?
          if /has\sbeen\sadded$/.match(response)
            break
          end
        end
      end
      menu.choice('List All Exercises') do
        exercise_controller.index
      end
      menu.choice('Create Workout') { say("") }
      menu.choice('View Workouts') { say("") }
      menu.choice('Exit') do
        say("Peace Out!\n")
        exit
      end
    end
  end
else
  puts "[Help] Run as: ./workout_generator manage"
end